/**
 * usePageSeo — one-liner per page to set all SEO meta tags.
 *
 * Sets: title, og:title, description, og:description, og:image (via nuxt-og-image),
 * og:url, twitter:card, twitter:title, twitter:description, twitter:image,
 * and canonical link.
 *
 * Dynamic OG images are generated by nuxt-og-image using Satori.
 * The default template is OgImageDefault; pass `ogImageComponent`
 * to use a different template (e.g. OgImageCategory).
 */
export function usePageSeo(opts: {
  title: string
  description: string
  image?: string
  type?: 'website' | 'article' | 'profile'
  ogImageComponent?: string
  ogImageProps?: Record<string, unknown>
}) {
  const route = useRoute()
  const runtimeConfig = useRuntimeConfig()
  const siteUrl = (runtimeConfig.public.appUrl || 'https://austin-texas.net').replace(/\/$/, '')
  const canonicalUrl = `${siteUrl}${route.path}`

  useSeoMeta({
    title: opts.title,
    ogTitle: opts.title,
    description: opts.description,
    ogDescription: opts.description,
    ogUrl: canonicalUrl,
    ogType: opts.type || 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: opts.title,
    twitterDescription: opts.description,
  })

  // If a static image is explicitly provided, use it directly.
  // Otherwise, let nuxt-og-image generate a dynamic OG image.
  if (opts.image) {
    useSeoMeta({
      ogImage: opts.image,
      twitterImage: opts.image,
    })
  }
  else if (import.meta.server) {
    // defineOgImage must only run server-side (SSR context).
    // See: https://github.com/nuxt-modules/og-image/pull/293
    defineOgImage({
      component: opts.ogImageComponent || 'OgImageDefault',
      title: opts.title,
      description: opts.description,
      ...opts.ogImageProps,
    })
  }

  useHead({
    link: [
      { rel: 'canonical', href: canonicalUrl },
    ],
  })
}
