/**
 * usePageSeo — one-liner per page to set all SEO meta tags.
 *
 * Sets: title, og:title, description, og:description, og:image,
 * og:url, twitter:card, twitter:title, twitter:description, twitter:image,
 * and canonical link.
 *
 * OG images are generated by a Nitro server route using
 * @cloudflare/pages-plugin-vercel-og (Satori on CF Workers).
 * The URL pattern is: /__og-image__/<template>?title=...&description=...
 */

/** Map component names to template slugs used in the OG image route */
const OG_TEMPLATE_MAP: Record<string, string> = {
  OgImageDefault: 'default',
  OgImageCategory: 'category',
  OgImageSubApp: 'sub-app',
  OgImageNeighborhood: 'neighborhood',
}

export function usePageSeo(opts: {
  title: string
  description: string
  image?: string
  type?: 'website' | 'article' | 'profile'
  ogImageComponent?: string
  ogImageProps?: Record<string, unknown>
}) {
  const route = useRoute()
  const runtimeConfig = useRuntimeConfig()
  const siteUrl = (runtimeConfig.public.appUrl || 'https://austin-texas.net').replace(/\/$/, '')
  const canonicalUrl = `${siteUrl}${route.path}`

  // Build the OG image URL
  let ogImageUrl: string
  if (opts.image) {
    // Explicit static image provided
    ogImageUrl = opts.image
  }
  else {
    // Generate dynamic OG image URL pointing to our Nitro route
    const templateSlug = OG_TEMPLATE_MAP[opts.ogImageComponent || 'OgImageDefault'] || 'default'
    const params = new URLSearchParams()
    params.set('title', opts.title)
    if (opts.description) params.set('description', opts.description)

    // Pass through any additional ogImageProps
    if (opts.ogImageProps) {
      for (const [key, value] of Object.entries(opts.ogImageProps)) {
        if (value !== undefined && value !== null && value !== '') {
          params.set(key, String(value))
        }
      }
    }

    ogImageUrl = `${siteUrl}/__og-image__/${templateSlug}?${params.toString()}`
  }

  useSeoMeta({
    title: opts.title,
    ogTitle: opts.title,
    description: opts.description,
    ogDescription: opts.description,
    ogUrl: canonicalUrl,
    ogType: opts.type || 'website',
    ogImage: ogImageUrl,
    twitterCard: 'summary_large_image',
    twitterTitle: opts.title,
    twitterDescription: opts.description,
    twitterImage: ogImageUrl,
  })

  useHead({
    link: [
      { rel: 'canonical', href: canonicalUrl },
    ],
  })
}
